---
 - hosts: all
   become: true
   vars:
     motto: Ansible Managed node by punopaughey
     item:
       user: khlvn
       pass: root
   tasks:
     - name: Installs Python3 and pip3
       apt: 
         name:
          - python3
          - python3-pip 
         state: latest
         update_cache: true

     - name: sets python3 and pip3 as default
       lineinfile:
         dest: ".bashrc"
         line: |
            alias python=python3
            alias pip=pip3

     - name: Installs Java-open-jdk 
       apt: name=openjdk-11-jdk state=latest

     - name: Installs MariaDB
       apt:
         name:
          - mariadb-client
          - mariadb-server

     - name: Starting the MariaDB server
       service: name=mariadb state=started enabled=true

     - name: creates database and table entry
       mysql_db:
         name: test
         state: present
     
     - name: add data to database  
#       copy: src=dump.sql dest=/tmp/dump.sql

       mysql_db: name=test state=import target=/tmp/dump.sql

     - name: creates motd banner
       debug:
         msg: '{{ motto }}'

     - name: creates user in linux
       user:
         name: "{{ item.user }}"
         password:  "{{ item.pass }}"
         state: present
